<div id="content">
    <!-- CONTENU DE L'ARTICLE -->
    <h1>Titre de l'article</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sollicitudin feugiat leo sed fermentum. Donec id metus urna. Sed tempor, augue vel mollis sodales, libero tortor commodo risus, at accumsan justo enim a lectus. Maecenas et pellentesque enim, eget dignissim metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque rutrum, nibh id luctus suscipit, lacus lacus maximus mauris, vel fermentum ipsum purus non massa. Vestibulum sit amet risus eget neque ultrices viverra quis vel odio. Nullam ullamcorper felis vel mi imperdiet, nec interdum felis ultrices. Vivamus mollis erat eu justo semper, a facilisis purus porttitor. Vivamus aliquet posuere metus, nec hendrerit enim accumsan tincidunt. Etiam bibendum viverra ipsum, in tincidunt metus mattis sed. Aenean blandit sed ligula in ultrices. Mauris mi nibh, finibus ut erat vel, luctus semper mi. Integer et arcu volutpat, malesuada ligula sit amet, convallis lacus. Fusce pellentesque, purus ac interdum sollicitudin, sapien mi efficitur ligula, quis aliquet nibh lectus eu est. Duis tempus leo vel placerat ultricies. Ut malesuada orci a ultricies mattis. Quisque eget nisi neque. Vestibulum sagittis, purus nec bibendum ullamcorper, velit elit porta odio, a aliquam tortor ante eu nisl. Donec at malesuada turpis. Cras quis hendrerit quam, vitae imperdiet eros. Mauris nisi justo, euismod sed efficitur vitae, congue id nisi. Mauris in neque mattis, volutpat lacus a, molestie mauris. Ut placerat nisi arcu, ac ornare leo pretium ultricies. Nunc varius magna sed blandit volutpat. Cras viverra eget est sed eleifend. Morbi leo sapien, bibendum malesuada dapibus dictum, mollis eu erat. Proin rutrum, est ut mollis hendrerit, neque velit faucibus est, vel vehicula lacus justo vitae risus.
        <br><br><br> Morbi sit amet fermentum ipsum. Morbi vitae facilisis mi. Donec lectus quam, vehicula nec posuere eu, finibus vel risus. Etiam ut pharetra orci. Suspendisse eget sapien gravida, dignissim eros non, porttitor purus. Aliquam augue lorem, interdum in scelerisque euismod, ultricies vel nulla. Nunc tempor elit vitae nulla auctor elementum. Pellentesque at velit metus. Proin sagittis venenatis sapien a ultricies. Duis orci mi, elementum suscipit velit et, efficitur fringilla est. Cras massa mi, efficitur nec dignissim ac, tempus quis tellus. Nunc fermentum nisi et metus vulputate, sit amet condimentum nisi ultrices. Sed vitae turpis placerat, interdum metus eu, ultrices erat. Maecenas luctus quam eu eros vulputate, mattis auctor elit scelerisque. Donec vitae condimentum turpis. Nulla quis ante placerat, ultricies tortor non, eleifend felis. Proin augue tortor, ornare vitae tincidunt a, tincidunt eget est. Pellentesque pellentesque pulvinar mattis. Integer tincidunt nisi accumsan aliquet rhoncus. In viverra fringilla tortor, non sagittis est rhoncus ac. Maecenas pellentesque, erat eu dictum auctor, tortor odio congue neque, et cursus metus turpis in metus. Morbi elementum sodales sem eu ultrices. Nam ultricies odio eget elit mattis lacinia. Praesent ut sodales justo. Maecenas porttitor mauris sed dui fermentum, ut vulputate tellus posuere. Sed pretium magna nec placerat euismod. Curabitur a aliquam risus. Vestibulum ornare neque sagittis rhoncus volutpat. Curabitur facilisis varius blandit. Integer in volutpat enim, nec consectetur tortor. Fusce aliquam pellentesque orci, vel cursus erat pretium quis. Proin metus risus, ultricies in sem eu, gravida pellentesque turpis. Sed mollis sollicitudin mauris, nec commodo nisl eleifend nec. Morbi tincidunt mattis congue.<br><br><br>
        Fusce vitae quam in justo blandit dignissim vitae eget odio. Mauris vitae ante massa. Nunc fringilla efficitur nibh nec bibendum. Vivamus ultrices mauris velit, eget accumsan ex volutpat vel. Proin fermentum ex vel tincidunt viverra. Nunc pharetra purus a dui efficitur, quis hendrerit dui pharetra. Fusce vitae felis et turpis condimentum vestibulum. Nam elementum aliquam est euismod venenatis. Aenean nulla ipsum, rutrum at nulla ac, molestie ultrices velit. Cras imperdiet ornare tortor ac viverra. Phasellus eu dui id ipsum fringilla consequat. Sed lacinia magna ac sapien accumsan, at aliquet risus fringilla. Vestibulum ligula quam, consequat non magna consequat, auctor malesuada lacus. Fusce neque ante, ultrices nec sem vitae, interdum iaculis ante. In mauris augue, laoreet nec nibh dignissim, consectetur fringilla lorem. Donec at felis nec sem condimentum sodales nec gravida urna. Nulla facilisi. Ut mollis, sem malesuada venenatis luctus, eros sem posuere ligula, eget malesuada diam turpis sit amet felis. In sit amet erat viverra mauris bibendum auctor nec ac nisl. Morbi rutrum erat felis, quis molestie magna rhoncus ut. Nunc placerat turpis sed orci ornare, elementum hendrerit enim facilisis. Maecenas sed porta nisl, id pellentesque magna. Donec volutpat nec nisl eget hendrerit. Phasellus auctor nibh eu blandit semper. Aliquam at lobortis turpis, nec sagittis turpis. Vestibulum mollis nisi nec felis imperdiet finibus. Pellentesque quis nunc non nulla congue commodo. Praesent lorem lectus, tincidunt vitae imperdiet et, ornare eget mauris. Etiam suscipit pretium leo, eget aliquam nunc. Sed vitae erat at lacus pellentesque porttitor nec non nisl. Fusce luctus pulvinar efficitur. Proin a rhoncus leo. Donec nec ipsum ultrices, facilisis massa non, maximus libero. Donec non nulla et dolor cursus ullamcorper sed ac nibh. Quisque ac arcu rutrum, volutpat quam vel, lacinia magna. In ultrices metus orci, venenatis faucibus metus mollis ut. Duis vitae libero ac justo pharetra pulvinar a quis purus. Fusce viverra vehicula augue non vehicula.<br><br><br>
        Maecenas id molestie tellus. Pellentesque nec vehicula tellus, vitae consectetur metus. Aliquam dolor turpis, semper non posuere eu, tempor non velit. Praesent commodo imperdiet eros non porta. Nulla iaculis mattis neque id blandit. Nullam auctor velit ut nisl interdum eleifend. Maecenas malesuada leo mi, mollis sollicitudin elit lobortis non. Morbi at velit vitae felis tincidunt viverra eu id velit. Curabitur tempor diam lorem, et pretium ex consequat nec. Ut in tellus sagittis nisl scelerisque elementum vel nec ligula. Morbi eros mauris, posuere eget lacinia vitae, placerat quis augue. </p>

    <div class="boutonsimple">
        <a href="?articles"><button>Revenir aux articles</button></a>
    </div>

    <!-- LISTE DE COMMENTAIRE -->
        <div id="commentaires">
            <form action="" method="post">
                <h6>Laisser un commentaire : <br>
                    <textarea></textarea> <br>
                    <input type="submit">
                </h6>
            </form>
            <hr>
            <h6>Ceci est un commentaire court <span class="small-italic"> - AUTEUR</span></h6>
            <hr>
            <h6>Ceci est un commentaire de taille moyenne, Ceci est un commentaire de taille moyenne <span class="small-italic"> - AUTEUR</span></h6>
            <hr>
            <h6>Ceci est un commentaire extremement long. Ceci est un commentaire extremement long. Ceci est un commentaire extremement long. Ceci est un commentaire extremement long. Ceci est un commentaire extremement long. <span class="small-italic"> - AUTEUR</span></h6>
            <hr>
    </div>
</div>